layout_spectrum: 0.1568297
name: AFabrica
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.1020236
  saturation: 0.2133221
  rhythmicContrast: 0.3962901
  brandColors:
    - '#211E1F'
    - '#9B2743'
    - '#EED484'
    - '#7FA9AE'
    - '#83754F'
typography_spectrum: 0.7225969
