name: A Fábrica
favicon: null
layout_spectrum: 0.74831
typography_spectrum: 0.7225969
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: A Fábrica
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211E1F'
    - '#9B2743'
    - '#EED484'
    - '#7FA9AE'
    - '#83754F'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.2133221
  rhythmicContrast: 0
purpose: []
