layout_spectrum: 0.1568297
name: AFabrica
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.234275
  lightness: 0.6180438
  saturation: 0.5210792
  rhythmicContrast: 0.2487352
  brandColors:
    - '#FFFFFF'
    - '#992944'
    - '#ECD289'
    - '#7FA9AC'
    - '#A94A61'
typography_spectrum: 0.7225969
